name: Staging deploy to Github Pages
on:
  push:
    branches: [ stage ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Set git identity
      run: |
        git config --global user.email "me@lmorchard.com"
        git config --global user.name "Les Orchard"        
    - name: Yarn install
      run: yarn install
    - name: Build for staging
      run: yarn run build:stage
      env:
        YOUTUBE_USER_ID: ${{ secrets.YOUTUBE_USER_ID }}
        YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
        YOUTUBE_KEY: ${{ secrets.YOUTUBE_KEY }}
        TWITCH_USERNAME: ${{ secrets.TWITCH_USERNAME }}
        TWITCH_USERID: ${{ secrets.TWITCH_USERID }}
        TWITCH_CLIENTID: ${{ secrets.TWITCH_CLIENTID }}
        TWITCH_ACCESSTOKEN: ${{ secrets.TWITCH_ACCESSTOKEN }}
        ACTIVITYPUB_USERNAME: ${{ secrets.ACTIVITYPUB_USERNAME }}
        ACTIVITYPUB_BASE_URL: ${{ secrets.ACTIVITYPUB_BASE_URL }}
        ACTIVITYPUB_PROFILE_URL: ${{ secrets.ACTIVITYPUB_PROFILE_URL }}
        ACTIVITYPUB_OUTBOX_URL: ${{ secrets.ACTIVITYPUB_OUTBOX_URL }}
        GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
        POCKETCASTS_EMAIL: ${{ secrets.POCKETCASTS_EMAIL }}
        POCKETCASTS_PASSWORD: ${{ secrets.POCKETCASTS_PASSWORD }}
        SPOTIFY_USERNAME: ${{ secrets.SPOTIFY_USERNAME }}
        SPOTIFY_CLIENTID: ${{ secrets.SPOTIFY_CLIENTID }}
        SPOTIFY_CLIENTSECRET: ${{ secrets.SPOTIFY_CLIENTSECRET }}
        SPOTIFY_ACCESS_TOKEN: ${{ secrets.SPOTIFY_ACCESS_TOKEN }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        GOODREADS_USER_ID: ${{ secrets.GOODREADS_USER_ID }}
        GOODREADS_USER_NAME: ${{ secrets.GOODREADS_USER_NAME }}
        GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
        GOODREADS_SECRET: ${{ secrets.GOODREADS_SECRET }}
    - name: Create .nojekyll
      run: touch build/.nojekyll
    - name: Deploy for staging
      run: npx gh-pages -t -d build -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
