name: Staging deploy to Github Pages
on:
  push:
    branches: [ stage ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.2.0
      uses: actions/setup-node@v1
      with:
        node-version: 14.2.0
    - name: Set git identity
      run: |
        git config --global user.email "me@lmorchard.com"
        git config --global user.name "Les Orchard"        
    - name: Yarn install
      run: yarn install
    - name: Build for staging
      run: yarn run build:stage
      env:
        YOUTUBE_USER_ID: ${{ secrets.YOUTUBE_USER_ID }}
        YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
        YOUTUBE_KEY: ${{ secrets.YOUTUBE_KEY }}
        TWITCH_USERNAME: ${{ secrets.TWITCH_USERNAME }}
        TWITCH_USERID: ${{ secrets.TWITCH_USERID }}
        TWITCH_CLIENTID: ${{ secrets.TWITCH_CLIENTID }}
        TWITCH_ACCESSTOKEN: ${{ secrets.TWITCH_ACCESSTOKEN }}
        TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        SPOTIFY_USERNAME: ${{ secrets.SPOTIFY_USERNAME }}
        SPOTIFY_CLIENTID: ${{ secrets.SPOTIFY_CLIENTID }}
        SPOTIFY_CLIENTSECRET: ${{ secrets.SPOTIFY_CLIENTSECRET }}
        SPOTIFY_ACCESS_TOKEN: ${{ secrets.SPOTIFY_ACCESS_TOKEN }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        GOODREADS_USER_ID: ${{ secrets.GOODREADS_USER_ID }}
        GOODREADS_USER_NAME: ${{ secrets.GOODREADS_USER_NAME }}
        GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
        GOODREADS_SECRET: ${{ secrets.GOODREADS_SECRET }}
    - name: Deploy for staging
      run: npx gh-pages -t -d build -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
